# Generated by Django 3.2.9 on 2022-07-18 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Vacation Name')),
                ('image', models.ImageField(default='default.jpg', upload_to='Images/', verbose_name='Image')),
                ('address', models.CharField(max_length=300, verbose_name='Venue Address')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Contact Phone')),
                ('arrDate', models.DateField(blank=True, max_length=50, verbose_name='Start Date')),
                ('leavDate', models.DateField(blank=True, max_length=50, verbose_name='End Date ')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, verbose_name='City Name')),
                ('name', models.CharField(max_length=150, verbose_name='Vacation Name')),
                ('image', models.ImageField(default='default.jpg', upload_to='Images/', verbose_name='Image')),
                ('address', models.CharField(max_length=300, verbose_name='Venue Address')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Contact Phone')),
                ('arrDate', models.DateField(blank=True, max_length=50, verbose_name='Start Date')),
                ('leavDate', models.DateField(blank=True, max_length=50, verbose_name='End Date ')),
                ('description1', models.TextField(blank=True, verbose_name='Package description 1')),
                ('description2', models.TextField(blank=True, verbose_name='Package description 2')),
                ('description3', models.TextField(blank=True, verbose_name='Package description 3')),
                ('prevPrice', models.FloatField(max_length=150, verbose_name='Previous Price')),
                ('latestPrice', models.FloatField(max_length=150, verbose_name='Latest Offer Price')),
            ],
        ),
        migrations.CreateModel(
            name='MemberUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Member Address')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Contact Phone')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='City')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='Email ')),
                ('members', models.PositiveIntegerField(default=1, verbose_name='Members Attending')),
                ('first_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Added Yet', max_length=150, verbose_name='Venue Name')),
                ('vacationDate', models.DateTimeField(max_length=150, null=True, verbose_name='Vacation Date')),
                ('web', models.URLField(blank=True, max_length=50, null=True, verbose_name='Website Address')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email Address')),
                ('description', models.TextField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(blank=True, to='vacations.MemberUsers')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacations.book')),
            ],
        ),
    ]
