# Generated by Django 3.2.9 on 2022-07-18 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberusers',
            name='first_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.touruser'),
            preserve_default=False,
        ),
    ]
