# Generated by Django 3.2.9 on 2023-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialrooms',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='specialrooms',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Contact Phone'),
        ),
    ]
