# Generated by Django 3.2.9 on 2022-07-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacations', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourAmount', models.CharField(blank=True, max_length=150, null=True, verbose_name='Amount per tour')),
                ('totalAmount', models.CharField(blank=True, max_length=150, null=True, verbose_name='Total Amount')),
                ('tourOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacations.packages')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.memberusers')),
                ('hotelChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.specialrooms')),
                ('tourChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.packages')),
            ],
        ),
    ]
