# Generated by Django 3.2.9 on 2022-07-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220718_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touruser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='touruser',
            name='password2',
        ),
    ]
